"use client";
import "./globals.css";
import Link from "next/link";
import { CiSettings, CiBoxList, CiCalendar } from "react-icons/ci";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const Menu = ({ title, icon, path }) => {
  const pathname = usePathname();
  return (
    <Link
      href={path}
      className={`${pathname === path ? "bg-green-primary" : ""}
      flex rounded-md hover:bg-green-primary`}
    >
      <div className="hidden sm:block  p-2  ">{title}</div>
      <div className=" sm:hidden text-2xl font-bold text-green-600 hover:scale-110">
        {icon}
      </div>
    </Link>
  );
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-5 bg-lightGray">
        {/* header */}
        <div className="flex justify-between ">
          <div className="flex">
            <div className="text-xl">Emplois du temps</div>
          </div>

          <div className="flex gap-4 justify-center items-center ">
            <Menu
              title="Emplois du temps"
              path="/timetable/student"
              icon={<CiCalendar />}
            />
            <Menu title="Activités" path="/activities" icon={<CiBoxList />} />
            <Menu
              title="Paramètres"
              path="/timetable_elements/majors"
              icon={<CiSettings />}
            />
          </div>
        </div>
        {/* main */}
        <main>{children}</main>
      </body>
    </html>
  );
}

// facebook.com/g
// facebook.com/i
// facebook.com/j
// facebook.com/p
// facebook.com/u
